version: '3.5'

services:
  cadastro-api-compose:
    image: juniorfredes/api:13
    ports:
      - "8080:8080"
    networks:
      - production-network
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:9.5
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
      - POSTGRES_DB=vagas-cadastro
      - PGDATA=/var/lib/postgresql/data/pgdatabase
    networks:
      - production-network
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  production-network:
    driver:
      bridge